In [1]:
import pandas as pd
import numpy as np
import glob
import os

In [2]:
os.getcwd()

'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant'

In [3]:
table_paths = glob.glob('C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant/*.tab')
table_paths

['C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122784_SAM24447555.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122785_SAM24447556.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122786_SAM24447557.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122787_SAM24447558.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122788_SAM24447559.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122789_SAM24447560.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122790_SAM24447561.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122791_SAM24447562.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122792_SAM24447567.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122793_SAM24447568.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122794_SAM24447569.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122795_SAM24447570.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122796_SAM24447571.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122797_SAM24447572.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122798_SAM24447573.counts_gene_coding.tab',
 'C:\\Users\\tobij\\Desktop\\Ipynb Tasks\\Giredestrant\\GSM8122799_SAM24447574.counts_gene_coding.tab']

In [4]:
dfs = []
for item in table_paths:
    dfs.append(pd.read_csv(item, delimiter='\t'))

In [5]:
df = pd.concat(dfs, axis=1)

In [6]:
df.head()

,name,count,width,rpkm,name,count,width,rpkm,name,count,...,width,rpkm,name,count,width,rpkm,name,count,width,rpkm
0,ENSG00000000003,918,744,39.963431,ENSG00000000003,1025,744,34.996932,ENSG00000000003,1182,...,744,29.110372,ENSG00000000003,684,744,24.064337,ENSG00000000003,706,744,26.240048
1,ENSG00000000005,0,954,0.000000,ENSG00000000005,0,954,0.000000,ENSG00000000005,0,...,954,0.000000,ENSG00000000005,0,954,0.000000,ENSG00000000005,0,954,0.000000
2,ENSG00000000419,1394,864,52.256708,ENSG00000000419,1739,864,51.128716,ENSG00000000419,2212,...,864,51.282366,ENSG00000000419,1854,864,56.167710,ENSG00000000419,1913,864,61.225746
3,ENSG00000000457,527,2229,7.657616,ENSG00000000457,569,2229,6.484571,ENSG00000000457,626,...,2229,6.788645,ENSG00000000457,799,2229,9.382692,ENSG00000000457,688,2229,8.535151
4,ENSG00000000460,847,2744,9.997521,ENSG00000000460,1058,2744,9.794462,ENSG00000000460,1354,...,2744,8.300952,ENSG00000000460,614,2744,5.856997,ENSG00000000460,653,2744,6.580546

In [7]:
df.columns

Index(['name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm',
       'name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm',
       'name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm',
       'name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm',
       'name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm',
       'name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm',
       'name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm',
       'name', 'count', 'width', 'rpkm', 'name', 'count', 'width', 'rpkm'],
      dtype='object')

In [8]:
np.where(df.isna().sum())

(array([], dtype=int64),)

In [9]:
counts = df['count']

In [10]:
counts_cols = counts.columns

In [11]:
new_names = []
for idx, item in enumerate(counts_cols):
    if idx < 4:
        new_names.append(f'dmso_control_{idx + 1}')
    elif idx >= 4 and idx < 8:
        new_names.append(f'dmso_GPX4_{idx - 3}')
    elif idx >= 8 and idx < 12:
        new_names.append(f'giredestrant_control_{idx - 7}')
    else:
        new_names.append(f'giredestrant_GPX4_{idx - 11}')

In [12]:
new_names

['dmso_control_1',
 'dmso_control_2',
 'dmso_control_3',
 'dmso_control_4',
 'dmso_GPX4_1',
 'dmso_GPX4_2',
 'dmso_GPX4_3',
 'dmso_GPX4_4',
 'giredestrant_control_1',
 'giredestrant_control_2',
 'giredestrant_control_3',
 'giredestrant_control_4',
 'giredestrant_GPX4_1',
 'giredestrant_GPX4_2',
 'giredestrant_GPX4_3',
 'giredestrant_GPX4_4']

In [13]:
counts.columns = new_names

In [14]:
counts

,dmso_control_1,dmso_control_2,dmso_control_3,dmso_control_4,dmso_GPX4_1,dmso_GPX4_2,dmso_GPX4_3,dmso_GPX4_4,giredestrant_control_1,giredestrant_control_2,giredestrant_control_3,giredestrant_control_4,giredestrant_GPX4_1,giredestrant_GPX4_2,giredestrant_GPX4_3,giredestrant_GPX4_4
0,918,1025,1182,1001,894,645,737,889,967,1157,1026,1233,472,677,684,706
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1394,1739,2212,1755,1738,1466,1483,1843,1053,1389,1423,1732,1350,1385,1854,1913
3,527,569,626,469,735,510,581,575,573,553,608,712,513,473,799,688
4,847,1058,1354,1059,1103,863,932,1004,277,328,339,352,454,712,614,653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20315,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20316,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20317,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20318,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20319,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
genes = df.iloc[:, 0]

In [16]:
genes = genes.to_frame()
genes.head()

              name
0  ENSG00000000003
1  ENSG00000000005
2  ENSG00000000419
3  ENSG00000000457
4  ENSG00000000460

In [17]:
df = pd.concat([genes, counts], axis=1)

In [18]:
df.head()

,name,dmso_control_1,dmso_control_2,dmso_control_3,dmso_control_4,dmso_GPX4_1,dmso_GPX4_2,dmso_GPX4_3,dmso_GPX4_4,giredestrant_control_1,giredestrant_control_2,giredestrant_control_3,giredestrant_control_4,giredestrant_GPX4_1,giredestrant_GPX4_2,giredestrant_GPX4_3,giredestrant_GPX4_4
0,ENSG00000000003,918,1025,1182,1001,894,645,737,889,967,1157,1026,1233,472,677,684,706
1,ENSG00000000005,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,ENSG00000000419,1394,1739,2212,1755,1738,1466,1483,1843,1053,1389,1423,1732,1350,1385,1854,1913
3,ENSG00000000457,527,569,626,469,735,510,581,575,573,553,608,712,513,473,799,688
4,ENSG00000000460,847,1058,1354,1059,1103,863,932,1004,277,328,339,352,454,712,614,653

In [19]:
df.shape

(20320, 17)

In [20]:
df.to_csv('counts.csv', index=False)

In [21]:
df.columns

Index(['name', 'dmso_control_1', 'dmso_control_2', 'dmso_control_3',
       'dmso_control_4', 'dmso_GPX4_1', 'dmso_GPX4_2', 'dmso_GPX4_3',
       'dmso_GPX4_4', 'giredestrant_control_1', 'giredestrant_control_2',
       'giredestrant_control_3', 'giredestrant_control_4',
       'giredestrant_GPX4_1', 'giredestrant_GPX4_2', 'giredestrant_GPX4_3',
       'giredestrant_GPX4_4'],
      dtype='object')

In [22]:
controls = df[['name', 'dmso_control_1', 'dmso_control_2', 'dmso_control_3', 'dmso_control_4', 'giredestrant_control_1', 'giredestrant_control_2', 'giredestrant_control_3', 'giredestrant_control_4']]

In [23]:
controls_cols = controls.columns

In [25]:
gpx4s = df.loc[:, ~df.columns.isin(controls_cols)]

In [29]:
gpx4s = pd.concat([genes, gpx4s], axis=1)

In [32]:
controls.to_csv('controls.csv', index=False)
gpx4s.to_csv('gpx4s.csv', index=False)